"""GitHub PR creation with real diff application (replaces the old placeholder).

Flow per fix:
  1. Fetch the current file content (contents API) — 404 => file missing.
  2. Validate the proposed new content (syntax) — invalid => NO PR (by spec).
  3. PUT the new content on a fresh branch `autofix/<shortid>-<ts>`.
  4. Open a PR with a full body (what changed, why, validation, risks).

All calls are sync httpx (FastAPI runs handlers in a threadpool).
"""
from __future__ import annotations

import base64

import httpx

from ...github_client import GITHUB_API, GitHubError, _headers, TIMEOUT


def fetch_file_content(token: str, full_name: str, path: str, branch: str) -> dict | None:
    """Return {'content', 'sha'} or None if the file does not exist on `branch`."""
    with httpx.Client(timeout=TIMEOUT, headers=_headers(token)) as client:
        resp = client.get(
            f"{GITHUB_API}/repos/{full_name}/contents/{path}",
            params={"ref": branch},
        )
    if resp.status_code == 404:
        return None
    if resp.status_code != 200:
        raise GitHubError(f"Failed to read {path} ({resp.status_code}): {resp.text[:300]}")
    data = resp.json()
    try:
        content = base64.b64decode(data.get("content", "")).decode("utf-8")
    except Exception as exc:
        raise GitHubError(f"Failed to decode {path}: {exc}")
    return {"content": content, "sha": data.get("sha")}


def _put_file(token, full_name, path, branch, sha, content, message) -> None:
    with httpx.Client(timeout=TIMEOUT, headers=_headers(token)) as client:
        payload = {
            "message": message,
            "content": base64.b64encode(content.encode("utf-8")).decode(),
            "branch": branch,
        }
        if sha:
            payload["sha"] = sha
        resp = client.put(f"{GITHUB_API}/repos/{full_name}/contents/{path}", json=payload)
    if resp.status_code not in (200, 201):
        raise GitHubError(f"Failed to write {path} on {branch} ({resp.status_code}): {resp.text[:300]}")


def create_pr_from_file_change(
    *,
    token: str,
    full_name: str,
    base_branch: str,
    head_branch: str,
    file_path: str,
    new_content: str,
    commit_message: str,
    title: str,
    body: str,
    current_sha: str | None,
) -> dict:
    """Apply a real file change + open the PR. Returns {'url', 'number'}."""
    _put_file(token, full_name, file_path, head_branch, current_sha, new_content, commit_message)

    with httpx.Client(timeout=TIMEOUT, headers=_headers(token)) as client:
        pr_resp = client.post(
            f"{GITHUB_API}/repos/{full_name}/pulls",
            json={"title": title, "head": head_branch, "base": base_branch, "body": body},
        )
    if pr_resp.status_code not in (200, 201):
        raise GitHubError(f"Failed to create PR ({pr_resp.status_code}): {pr_resp.text[:300]}")
    pr = pr_resp.json()
    return {"url": pr.get("html_url"), "number": pr.get("number")}


def build_pr_body(*, rule_title: str, description: str, file_path: str, diff: str,
                  validation: str, confidence: float | None, severity: str) -> str:
    """Rich, honest PR description per the user's spec."""
    head = [
        f"## What changed",
        f"`{file_path}` updated to resolve: **{rule_title}**.",
        "",
        f"## Why",
        description,
        "",
        f"## Validation",
        validation,
        "",
        f"- Severity: `{severity}`",
        f"- Confidence: `{(confidence or 0) * 100:.0f}%`",
        "",
        "> ⚠️ Automated change generated by Breaklytix. Review before merging.",
        "",
        "### Diff",
        "```diff",
        diff or "(no diff produced)",
        "```",
        "",
    ]
    return "\n".join(head)